name: Node.js CI

on:
  push:
    paths:
      - .github/workflows/typescript.yml
      - cheese-finder-api/**
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    paths:
      - .github/workflows/typescript.yml
      - cheese-finder-api/**

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install all modules
      run: npm ci
      working-directory: ./cheese-finder-api

    - name: Lint
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm run lint
      working-directory: ./cheese-finder-api

    - name: Format
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm run format
      working-directory: ./cheese-finder-api

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm run test
      working-directory: ./cheese-finder-api

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download all modules
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: |
        npm ci
        npm run build
      working-directory: ./cheese-finder-api
