# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    paths:
      - .github/workflows/typescript.yml
      - cheese-finder-api/**
    tags:
      - '*'
    branches:
      - '*'
  pull_request:
    paths:
      - .github/workflows/typescript.yml
      - cheese-finder-api/**
      
defaults:
  run:
    working-directory: ./cheese-finder-api
    
jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install all modules
    - uses: actions/checkout@v3
    - run: npm ci
      
    - name: Lint 
    - uses: actions/setup-node@v3
      with:
        node-version: 21
    - run: npm run lint

    - name: Format
    - uses: actions/setup-node@v3
    - run: npm run format

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - run: npm run test
    
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
     
      - name: Download all modules
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'npm'
      - run: npm ci
      - run: npm run build 
