name: Node.js CI

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all modules
        run: npm ci

      - name: Lint
        uses: actions/setup-node@v3
        with:
          node-version: 21
          check-latest: true
      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all modules
        run: npm ci

      - name: Run tests
        uses: actions/setup-node@v3
        with:
          node-version: 21
          check-latest: true
      - run: npm run test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all modules
        uses: actions/setup-node@v3
        with:
          node-version: 21
          check-latest: true
      - run: |
          npm ci
          npm run build
