name: Node.js CI

on:
  push:
    tags:
      - '*'
    branches:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all modules
        run: npm ci

      - name: Lint
        uses: actions/setup-node@v3
        with:
          node-version: 21
          check-latest: true
      - run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install all modules
        run: npm ci

      - name: Run tests
        uses: actions/setup-node@v3
        with:
          node-version: 21
          check-latest: true
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download all modules
        uses: actions/setup-node@v3
        with:
          node-version: 21
          check-latest: true
      - run: |
          npm ci
          npm run install

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Clever Cloud
        if: startsWith(github.ref, 'refs/tags/')
        uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: app_37f52907-b29d-492b-89fa-ca3ced90aa45
          setEnv: |
            PORT=8080
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
